%>@ingroup idata
%>@file
%>@brief Welcome message

function s = get_welcome()

s = sprintf([
' * \n' ...
' * Welcome to IRootLab.\n', ...
' * \n' ...
' * Quick start:\n *\n' ...
' *   - User Interfaces: <a href="matlab: objtool">objtool</a>, <a href="matlab: mergetool">mergetool</a>, <a href="matlab: irootlabgui">irootlabgui</a>\n *\n' ...
' *   - Read the <a href="matlab: help2">Documentation</a>\n *\n' ...
' *   - Website: <a href="http://irootlab.googlecode.com">http://irootlab.googlecode.com</a>\n *\n' ...
' *\n']);
