%>@ingroup idata
%>@file
%>@brief Welcome message

function s = get_welcome()

s = sprintf([
' * \n' ...
' * Welcome to IRoot.\n', ...
' * \n' ...
' * Quick start:\n *\n' ...
' *   - Read the <a href="matlab: iroothelp">Documentation</a>\n *\n' ...
' *   - Website: <a href="http://bioph.lancs.ac.uk/iroot">http://bioph.lancs.ac.uk/iroot</a>\n *\n' ...
' *   - User Interfaces: <a href="matlab: datatool">datatool</a>, <a href="matlab: objtool">objtool</a>, <a href="matlab: mergetool">mergetool</a>, <a href="matlab: irootgui">irootgui</a>\n *\n' ...
' *\n']);
