%> @brief Log generated by a @ref gridsearch
classdef log_gridsearch < irlog
    properties
        %> Array of sovalues
        sovaluess = sovalues.empty();
        
        % Other stuff??
    end;

    methods
        function o = log_gridsearch()
            o.classtitle = 'Grid search';
            o.moreactions = [o.moreactions, {'extract_sovaluess'}];
            o.flag_ui = 0;
        end;
    end;
    
    methods
        %> Extracts fold-wise blocks
        function out = extract_sovaluess(o)
            for i = 1:numel(o.sovaluess)
                out{i} = o.sovaluess(i);
            end;
        end;
    end;
end
