%> This SODATAITEM is generated by a FeaHistGenerator
classdef soitem_fhg < soitem_sostagechoice
    properties
        %> A @ref log_fselrepeater object
        log;
        stab;
        s_methodology;
    end;
end
