/**
@mainpage Main Page

@section main_intro Introduction

IRoot is an open-source project dedicated to providing a MATLAB framework for  biospectroscopy. The goal of the IRoot project to provide a
comprehensive and user-friendly environment for analysis, and at the same time facilitate the development and validation of algorithms
for biospectroscopy.

Project website: http://iroot-matlab.googlecode.com

@section gettingstarted_install Installation

Download the most recent ZIP file from http://iroot-matlab.googlecode.com, and extract the file into a directory of your choice.

@section gettingstarted Getting started

The recommended way is to add the required directories to path after starting MATLAB:
<ol>
  <li> Start MATLAB </li>
  <li> Change MATLAB's "Current directory" to the directory created when unzipping IRoot (should contain a file called "startup.m")</li>
  <li> In MATLAB's command line, enter
@code
startup
@endcode
This will set the MATLAB path.</li>
  <li> You are ready to use IRoot!</li>
</ol>

This methods is the safest, as you will keep your MATLAB path "clean", being less likely to have name conflicts with other toolboxes and between different IRoot versions.

Alternatively, you can use MATLAB "Set path..." (add with subdirectories), and point to the directory above. This will keep you from having to run "startup" every time you
start MATLAB. Make sure you remove the old directories from the path when you download a new version of IRoot.

@subsection gettingstarted_requirements System requirements

IRoot will run wherever MATLAB can be installed. The oldest MATLAB version tested was r2007b.

Recently, we have been using MATLAB Parallel Computing Toolbox (PCT) to paralellize certain algorithms, but there is always a choice to run the non-parallel version.

We use the MATLAB Wavelet Toolbox for Wavelet de-noising.

<h3>gettingstarted_requirements2 Platform-specific binaries</h3>

@arg SVM classifier (LibSVM): LibSVM was successfully compiled for Windows 32-bit/Windows 64-bit; Linux 32-bit/64-bit.
@arg MySQL connector (mYm): mYm was currently compiled Windows 32-bit; Linux 32-bit/64-bit. Linux 64-bit: libmysqlclient.so.16 and  libmysqlclient.so.18.

@subsection gettingstarted_guis Graphical user interfaces (GUIs)

<table>
<tr>
  <td><b>GUI name</b></td>
  <td><b>Purpose</b></td>
  <td><b>Documentation page</b></td>
<tr>
  <td><code>datatool</code></td>
  <td>Manage and visualize data</td>
 <td>@ref datatool.m</td>
</tr>
<tr>
  <td><code>objtool</code></td>
  <td>Manage and visualize all types of objects</td>
 <td>@ref objtool.m</td>
</tr>
<tr>
  <td><code>mergetool</code></td>
  <td>Merge many single-spectrum files into a dataset</td>
 <td>@ref mergetool.m</td>
</tr>
<tr>
  <td><code>iroot</code></td>
  <td>Launch other GUIs, get help, and view auto-code</td>
 <td>@ref irootgui.m</td>
</tr>
</table>

@subsection gettingstarted_types Supported file types

The following file types are supported within datatool:

<table>
<tr>
  <td><b>File type</b></td>
  <td><b>Read?</b></td>
  <td><b>Write?</b></td>
  <td><b>Comment</b></td>
  <td><b>Related OOP-class</b></td>
</td>
<tr>
  <td>TXT (basic)</td>
  <td>Yes</td>
  <td>Yes</td>
  <td>Figure 1</td>
  <td>@ref dataio_txt_basic.m</td>
</tr>
<tr>
  <td>TXT ("Pirouette-like")</td>
  <td>Yes</td>
  <td>Yes</td>
  <td>Figure 1</td>
  <td>@ref dataio_txt_pir.m</td>
</tr>
<tr>
  <td>TXT (IRoot)</td>
  <td>Yes</td>
  <td>Yes</td>
  <td>Figure 2; Currently very slow, but more flexible than other TXT formats</td>
  <td>@ref dataio_txt_iroot.m</td>
</tr>
<tr>
  <td>MAT</td>
  <td>Yes</td>
  <td>Yes</td>
  <td>MATLAB compressed binary: short file size; opens fast</td>
  <td>@ref dataio_txt_mat.m</td>
</tr>
<tr>
  <td>OPUS image maps</td>
  <td>Yes</td>
  <td>No</td>
  <td></td>
  <td>@ref dataio_opus_nasse.m</td>
</tr>
</table>

<h3>Notes about file types</h3>

Currently, the best TXT format to export/import to/from Excel is the "TXT (Pirouette-like)". This format does not save all the properties of the dataset (for example, the spectrum file name is lost).
The "IRoot" format is complete, but not very well designed. We are currently working on a new text format that will be complete, fast, and easy to edit in Excel.

@image html dataformat.png
<center>Figure 1 - "Basic" and "Pirouette-like" text formats</center>

@image html dataformat_iroot.png
<center>Figure 2 - "IRoot" text format</center>

@subsection gettingstarted_more More

@arg Read the @ref highguide
@arg Follow the step-by-step tutorials at http://bioph.lancs.ac.uk/iroot
@arg Check the @ref demo
@arg Checking the autogenerated MATLAB code is a quick way to learn how to use the API


*/
