/**
@mainpage Main Page

@section main_intro Introduction

IRootLab is a framework for vibrational spectroscopy data analysis in MATLAB. It provides pattern recognition, biomarker extraction, imaging, pre-processing methods etc, applied to vibrational spectroscopy. IRootLab is Open-Source and Free/Libre software with a LGPL licence.

Vibrational spectroscopy includes Fourier-transform infrared (FTIR) and Raman spectroscopy.

Project website: http://irootlab.googlecode.com

@section thisdoc This documentation

This documentation is the library reference. It was generated by Doxygen directly from the source code. From MATLAB command line, <code>help2('filename')</code> opens a page from this reference. Pressing F1 on a graphical user interface (GUI) calls the context-sensitive help.

Files have been grouped in "modules" (left) mostly to try to facilitate navigation. The class hierarchy allows browsing the OOP class inheritance structure. Other options are indexes created by Doxygen.

For a friendly start, please check http://code.google.com/p/irootlab/downloads/list. Resources provided include a manual, tutorials, software, and data.

@section gettingstarted Quick getting started

<ol>
  <li> Download the most recent ZIP file from http://code.google.com/p/irootlab/downloads/list and extract the file into a directory of your choice
  <li> Start MATLAB </li>
  <li> Change MATLAB's "Current directory" to the one created above (which should contain a file called "startup.m")</li>
  <li> In MATLAB's command line, enter
@code
startup
@endcode
This will set the MATLAB path.</li>
  <li> The welcome message gives some click options, such as checking the demos, or running @c mergetool or @c objtool</li>
</ol>

@subsection gettingstarted_requirements System requirements

MATLAB (Windows/Linux/MacOS/etc) release >= r2007b

Some routines offer a "parfor" version of algorithms (MATLAB Parallel Computing Toolbox (PCT)), but the routines work without the PCT.

MATLAB Wavelet Toolbox for Wavelet de-noising.

<h3>gettingstarted_requirements2 Platform-specific binaries</h3>

@arg SVM classifier (LibSVM): LibSVM was successfully compiled for Windows 32-bit/Windows 64-bit; Linux 32-bit/64-bit.
@arg MySQL connector (mYm): mYm was currently compiled Windows 32-bit; Linux 32-bit/64-bit. Linux 64-bit: libmysqlclient.so.16 and  libmysqlclient.so.18.
*/
