%>@brief Carries a "grades" vector; usually generated by a @ref as_grades object
classdef log_grades < irlog
    properties
        %> Grades vector
        grades;
        
        %> Extracted from data
        fea_x;
        %> Extracted from data
        xname = '';
        %> Extracted from data
        xunit;
        %> Describes what the "grades" represent
        yname;
        %> Describes what the "grades" represent
        yunit;
    end;
    
    properties
        nf;
    end;
    
    methods
        function n = get.nf(o)
            n = numel(o.fea_x);
        end;
    end;
end