%> @brief Model comparison log
%> @todo Is it true that this class is going to vanish?
%>
%> Generated by reptt_sgs::extract_comparison()
%>
%> Example of output generated by do_get_explanation()
%>@verbatim
%>                             clssr_cla type = linear clssr_cla type = quadratic clssr_dist
%> clssr_cla type = linear                       0.00                       2.91       3.71
%> clssr_cla type = quadratic                   -2.91                       0.00       3.02
%> clssr_dist                                   -3.71                      -3.02       0.00
%>@endverbatim
%>
%> In the example above, positive values mean the classifier in the row is better when compared with the classifier in
%> the column
classdef log_comparison < irlog
    properties
        %> [no_blocks][no_blocks] Comparison matrix
        M;
        %> Row and column labels indistincively
        labels;
    end;

    methods
        function o = log_comparison()
            o.classtitle = 'Comparison';
            o.flag_ui = 0;
        end;
    end;

            
    
    methods(Access=protected)
        function s = do_get_html(o)
            s = [do_get_html@irlog(), html_confusion(o.M, o.labels, o.labels, 0, 0, 0)];
        end;
    end;
end

